name: rubocop
on: [push]
jobs:
  run:
    name: Run Rubocop
    runs-on: ubuntu-latest

    container:
      image: ruby:3.2.2
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: cache bundle gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: install bundler
        run: gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: run rubocop
        run: bundle exec rubocop
